version: "3"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
    networks:
      - flipt_network

  flipt:
    image: markphelps/flipt:latest
    depends_on:
      - jaeger
    ports:
      - "8080:8080"
    networks:
      - flipt_network
    environment:
      - "FLIPT_LOG_LEVEL=debug"
      - "FLIPT_TRACING_JAEGER_ENABLED=true"
      - "OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger"
      - "OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces"

networks:
  flipt_network:
